version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: m@sterkey
      MYSQL_DATABASE: desafio_vr_db
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
