"""03-AddedBinaryImageFieldInProductd

Revision ID: 85abbc483d4d
Revises: 509ae745570c
Create Date: 2024-10-30 21:33:52.320399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85abbc483d4d'
down_revision = '509ae745570c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=mysql.LONGBLOB(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
