"""01-AddTableProductAndLoja

Revision ID: 88047941fe7d
Revises: 
Create Date: 2024-10-30 20:52:46.008157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88047941fe7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    ## dados iniciais tabela loja
    op.execute("""
        INSERT INTO loja (id, descricao) VALUES
        (1, 'Loja 1'),
        (2, 'Loja 2'),
        (3, 'Loja 3')   
    """)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=False),
    sa.Column('custo', sa.Numeric(precision=13, scale=3), nullable=True),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    op.drop_table('loja')
    # ### end Alembic commands ###
